### ISSUE TITLE
Startup-Exception "jdbcUrl is required with driverClassName"

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/ServerStatsDB#3]
```
[01:22:58 INFO]: [ServerStatsDB] Using com.mysql.cj.jdbc.Driver database driver
[01:22:58 ERROR]: [ServerStatsDB] [STDERR] [Craft Scheduler Thread - 3] ERROR de.themoep.serverstatsdb.shaded.hikari.HikariConfig - HikariPool-1 - jdbcUrl is required with driverClassName.
[01:22:58 WARN]: Nag author(s): '[Phoenix616]' of 'ServerStatsDB' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[01:22:58 WARN]: [ServerStatsDB] Plugin ServerStatsDB v1.1.1-SNAPSHOT (build 20) generated an exception while executing task 38
java.lang.IllegalArgumentException: jdbcUrl is required with driverClassName.
        at de.themoep.serverstatsdb.shaded.hikari.HikariConfig.validate(HikariConfig.java:971) ~[ServerStatsDB.jar:?]
        at de.themoep.serverstatsdb.shaded.hikari.HikariDataSource.getConnection(HikariDataSource.java:109) ~[ServerStatsDB.jar:?]
        at de.themoep.serverstatsdb.storage.MySqlStorage.getConn(MySqlStorage.java:118) ~[ServerStatsDB.jar:?]
        at de.themoep.serverstatsdb.storage.MySqlStorage.<init>(MySqlStorage.java:71) ~[ServerStatsDB.jar:?]
        at de.themoep.serverstatsdb.ServerStatsDB.lambda$loadConfig$0(ServerStatsDB.java:79) ~[ServerStatsDB.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-204]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [patched_1.17.1.jar:git-Paper-204]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-204]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]

```

- ServerStatsDB v1.1.1-SNAPSHOT (build 20)
- DB Server-Version: 8.0.26 - MySQL Community Server - GPL (Protokoll-Version: 10)

**Comment by Phoenix616** [comment]
Should be fixed with c54b2f1
